version: '3.8'
services:
  nginx-testes:
    image: nginx:1-alpine
    ports:
      -  ${FRONT_PORT}:80
    volumes:
      - ${FRONT_VOLUME}:/usr/share/nginx/html
    container_name: ${CONTAINER_NAME}
    network_mode: worknet
    restart: unless-stopped